inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - data/**/*
    - config/**/*

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/lib/traject/macros/date_parsing_spec.rb

# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*_spec.rb'

Style/AsciiComments:
  Enabled: false

Style/WordArray:
  Enabled: false
