inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - data/**/*

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 125
  Exclude:
    - 'spec/lib/traject/macros/date_parsing_spec.rb'
    - 'traject_configs/**/*'

# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/macros/date_parsing.rb'

Performance/StringReplacement:
  Exclude:
    - 'traject_configs/**/*'

Style/AsciiComments:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'traject_configs/**/*'

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - 'spec/lib/traject/macros/date_parsing_spec.rb'

Style/WordArray:
  Enabled: false
